
[functions.discord-interaction]
enabled = true
verify_jwt = true
import_map = "./functions/discord-interaction/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/discord-interaction/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/discord-interaction/*.html" ]

[functions.daily-sunrise-protocol]
enabled = true
verify_jwt = true
import_map = "./functions/daily-sunrise-protocol/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/daily-sunrise-protocol/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/daily-sunrise-protocol/*.html" ]
